-- MySQL Script generated by MySQL Workbench
-- mar. 03 nov. 2020 16:09:05 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema petitscracks
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema petitscracks
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `petitscracks` ;
USE `petitscracks` ;

-- -----------------------------------------------------
-- Table `petitscracks`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petitscracks`.`color` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dog_color` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petitscracks`.`age_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petitscracks`.`age_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  `label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petitscracks`.`gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petitscracks`.`gender` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gender` VARCHAR(10) NOT NULL,
  `label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petitscracks`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petitscracks`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dog_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petitscracks`.`dog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petitscracks`.`dog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `picture` VARCHAR(255) NOT NULL,
  `birthday` DATE NOT NULL,
  `description` LONGTEXT NULL,
  `link_chiendefrance` VARCHAR(255) NULL,
  `lof_number` VARCHAR(100) NULL,
  `is_dna_tested` TINYINT NULL,
  `gender_id` INT NOT NULL,
  `color_id` INT NOT NULL,
  `age_category_id` INT NOT NULL,
  `status_id` INT NOT NULL,
  `mother_id` INT NULL,
  `father_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`color_id` ASC) VISIBLE,
  INDEX `id_idx1` (`age_category_id` ASC) VISIBLE,
  INDEX `sex_id_idx` (`gender_id` ASC) VISIBLE,
  INDEX `status_id_idx` (`status_id` ASC) VISIBLE,
  INDEX `mother_id_idx` (`mother_id` ASC) VISIBLE,
  INDEX `father_id_idx` (`father_id` ASC) VISIBLE,
  CONSTRAINT `color_id`
    FOREIGN KEY (`color_id`)
    REFERENCES `petitscracks`.`color` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `age_category_id`
    FOREIGN KEY (`age_category_id`)
    REFERENCES `petitscracks`.`age_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gender_id`
    FOREIGN KEY (`gender_id`)
    REFERENCES `petitscracks`.`gender` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `status_id`
    FOREIGN KEY (`status_id`)
    REFERENCES `petitscracks`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `mother_id`
    FOREIGN KEY (`mother_id`)
    REFERENCES `petitscracks`.`dog` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `father_id`
    FOREIGN KEY (`father_id`)
    REFERENCES `petitscracks`.`dog` (`id`)
    ON DELETE NO ACTIONa va
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petitscracks`.`actuality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petitscracks`.`actuality` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
